<a href="https://colab.research.google.com/github/Anjelene-antonisamy/Python-Data/blob/main/Copy_of_Interrogating_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Interrogating the dataframe
---

We use pandas to create dataframes from data sets in files or online tables.

Once we have the dataframe we might want to:  
*   display a subset of rows
*   *   we can do this using df.head(), df.tail() or df.iloc[index]
*   display a subset of columns
*   *   we can do this using the column name as the key, e.g.   
`                df['rain (mm)']`  
*   *   we can display more than one column, simply by listing the columns in the square brackets, e.g.   
`                df[['rain (mm)', 'tmin (degC)', 'sun (hours)']]`  
*   *   and can dislay a subset of rows for a subset of columns, e.g.  
 `               df[['rain (mm)', 'tmax (degC)']].head(10)`

### Exercise 1 - get the data, look at first 10 records
---


1.  Import the pandas library with the alias pd  
2.  Read the sheet with the name "Industry Migration" from the Excel file from this link: https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true  (*Hint:  use pd.read_excel(url, sheet_name="Industry Migration") with the above url.*)
3.  display the first 10 rows of the data

In [21]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Industry Migration")
df.head(10)

,country_code,country_name,wb_income,wb_region,isic_section_index,isic_section_name,industry_id,industry_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
0,ae,United Arab Emirates,High income,Middle East & North Africa,C,Manufacturing,1,Defense & Space,378.74,127.94,8.20,68.51,49.55
1,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,3,Computer Hardware,100.97,358.14,112.98,149.57,182.22
2,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,4,Computer Software,1079.36,848.15,596.48,409.18,407.41
3,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,5,Computer Networking,401.46,447.39,163.99,236.69,188.07
4,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,6,Internet,1840.33,1368.42,877.71,852.39,519.40
5,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,8,Telecommunications,676.91,676.11,365.96,283.59,281.91
6,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,9,Law Practice,694.50,529.50,362.83,356.56,147.83
7,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,10,Legal Services,661.10,665.65,462.30,475.62,255.21
8,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,11,Management Consulting,982.85,694.25,520.28,574.60,406.03
9,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,12,Biotechnology,1230.17,846.28,500.77,205.78,513.23

### Exercise 2 - display just two columns

Display the first 50 records focusing on the industries where migration is happening in each country (show just country_name and industry_name).

In [31]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Industry Migration")
df.head()
df.iloc[:, [7,11]]

              country_name                       industry_name
0     United Arab Emirates                     Defense & Space
1     United Arab Emirates                   Computer Hardware
2     United Arab Emirates                   Computer Software
3     United Arab Emirates                 Computer Networking
4     United Arab Emirates                            Internet
...                    ...                                 ...
5290              Zimbabwe                     Mining & Metals
5291              Zimbabwe                    Higher Education
5292              Zimbabwe               International Affairs
5293              Zimbabwe   Information Technology & Services
5294              Zimbabwe  Non-Profit Organization Management

[5295 rows x 2 columns]

### Exercise 3 - yearly migration

*   display the middle 20 records, showing the country_name and the migration for each of the years 2015 to 2019.
---

In [38]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Industry Migration")
df.iloc[2648:2668, 7:14]

,industry_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
2648,Renewables & Environment,24.01,27.84,-9.85,-29.43,-63.83
2649,"Glass, Ceramics & Concrete",-17.74,-27.67,-19.57,-63.91,-50.87
2650,Packaging & Containers,-26.23,-21.12,-26.23,-40.06,-55.07
2651,Industrial Automation,-75.42,-71.15,-57.01,-95.02,-106.56
2652,Government Relations,-40.41,-2.47,-40.18,-70.58,-142.21
2653,Defense & Space,290.14,396.01,175.95,396.23,318.73
2654,Telecommunications,23.68,-148.03,-157.05,-87.85,-38.84
2655,Retail,-138.81,-662.75,-273.35,-109.23,0.00
2656,Hospitality,-718.56,-623.25,-446.93,-456.94,95.72
2657,Construction,332.56,-250.76,-289.17,-415.17,50.52
2658,Civil Engineering,0.00,-159.19,22.47,0.00,253.34
2659,Oil & Energy,154.70,-363.65,-241.73,100.40,132.11
2660,Higher Education,174.18,87.84,27.48,55.44,73.64
2661,Education Management,0.00,49.13,-21.01,-5.91,82.91
2662,Military,-46.82,-555.56,-292.15,-132.78,-29.89
2663,International Affairs,434.67,154.39,66.13,95.98,245.83
2664,Information Technology & Services,137.84,-160.08,-55.19,-140.85,95.04
2665,Non-Profit Organization Management,590.52,543.22,150.19,79.12,25.88
2666,Security & Investigations,-25.80,-97.81,-70.32,-43.80,159.59
2667,International Trade & Development,529.91,311.31,208.30,530.05,315.58

### Exercise 4 - migration to and from
---

The Excel file at this link (which you have already opened above): https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true has three data sheets, "Country Migration", "Industry Migration" and "Skills Migration"

Open the data sheet "Country Migration" and display the first 10 records showing the country that migration was to, the country it was from and the net migration for each year from 2015 to 2019

In [46]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name= "Country Migration")
df.head(10)
df.iloc[:, [1,7,12,13,14,15,16]]

,base_country_name,target_country_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
0,United Arab Emirates,Afghanistan,0.19,0.16,0.11,-0.05,-0.02
1,United Arab Emirates,Algeria,0.19,0.25,0.57,0.55,0.78
2,United Arab Emirates,Angola,-0.01,0.04,0.11,-0.02,-0.06
3,United Arab Emirates,Argentina,0.16,0.18,0.04,0.01,0.23
4,United Arab Emirates,Armenia,0.10,0.05,0.03,-0.01,0.02
...,...,...,...,...,...,...,...
4143,Zimbabwe,South Africa,-2.98,-11.79,-9.10,-12.08,-20.76
4144,Zimbabwe,United Arab Emirates,-2.50,-2.49,-2.21,-1.68,-3.19
4145,Zimbabwe,United Kingdom,3.91,4.66,0.74,-0.66,-1.97
4146,Zimbabwe,United States,38.60,37.76,10.09,6.06,5.25
4147,Zimbabwe,Zambia,0.70,2.47,0.83,1.21,0.33

### Exercise 5 - unique countries

Using the "Country Migration" sheet, get all the unique country names from where people have migrated (base_country_name) and use a for loop to print a list of the countries.

In [50]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Country Migration")
df['base_country_name'].unique()
for country in df["base_country_name"].unique():
 print(country)

United Arab Emirates
Afghanistan
Albania
Armenia
Angola
Argentina
Austria
Australia
Azerbaijan
Bosnia and Herzegovina
Bangladesh
Belgium
Burkina Faso
Bulgaria
Bahrain
Benin
Bolivia
Brazil
Bahamas, The
Botswana
Belarus
Canada
Congo, Dem. Rep.
Switzerland
Cote d'Ivoire
Chile
Cameroon
China
Colombia
Costa Rica
Cuba
Cyprus
Czech Republic
Germany
Denmark
Dominican Republic
Algeria
Ecuador
Estonia
Egypt, Arab Rep.
Spain
Ethiopia
Finland
Fiji
France
Gabon
United Kingdom
Georgia
Ghana
Greece
Guatemala
Hong Kong SAR, China
Honduras
Croatia
Haiti
Hungary
Indonesia
Ireland
Israel
India
Iraq
Iran, Islamic Rep.
Iceland
Italy
Jamaica
Jordan
Japan
Kenya
Cambodia
Korea, Rep.
Kuwait
Kazakhstan
Lebanon
Sri Lanka
Lithuania
Luxembourg
Latvia
Libya
Morocco
Moldova
Madagascar
Macedonia, FYR
Mali
Myanmar
Mongolia
Malta
Mauritius
Malawi
Mexico
Malaysia
Mozambique
Namibia
Nigeria
Nicaragua
Netherlands
Norway
Nepal
New Zealand
Oman
Panama
Peru
Papua New Guinea
Philippines
Pakistan
Poland
Puerto Rico
West Bank and Gaza
Portugal
Paraguay
Qatar
Romania
Serbia
Rwanda
Saudi Arabia
Sudan
Sweden
Singapore
Slovenia
Slovak Republic
Senegal
El Salvador
Syrian Arab Republic
Togo
Thailand
Tunisia
Turkey
Trinidad and Tobago
Taiwan, China
Tanzania
Ukraine
Uganda
United States
Uruguay
Uzbekistan
Venezuela, RB
Vietnam
Yemen, Rep.
South Africa
Zambia
Zimbabwe

### Exercise 6 - how many countries are migrated to

Using the "Country Migration" sheet again, get all the unique country names to where people have migrated and display the number of unique countries.

In [57]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Country Migration")
df['base_country_name'].nunique()

140

### Exercise 7 - skill sets
---


Using the "Skill Migration" data sheet, display the following:
*  the first record
*  the last 10 records
*  records from index 500 to index 600  
*  a count of all unique countries
*  a list of all unique skill group categories
*  the first 50 rows, skill group names and net migration in 2019 only

In [86]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name= "Skill Migration")
df.head(1)
df.tail(10)
df.iloc[500:601]
df['country_name'].nunique()
df['skill_group_category'].unique()
df.head(50)
df.iloc[:, [6,8,9,10,11]]

,skill_group_name,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
0,Information Management,-705.88,-550.04,-680.92,-1208.79
1,Operational Efficiency,-933.55,-776.06,-532.22,-790.09
2,National Security,-769.68,-756.59,-600.44,-767.64
3,Software Testing,-828.54,-964.73,-406.50,-739.51
4,Navy,-841.17,-842.32,-581.71,-718.64
...,...,...,...,...,...
17612,Teaching,30.68,-18.85,-68.89,-93.70
17613,Mining,-112.85,-35.87,-65.38,-93.46
17614,Personal Coaching,-59.70,-88.01,-55.90,-82.23
17615,Public Health,-65.53,-57.22,-39.39,-32.14
17616,Law,47.16,-31.24,-8.24,-25.52

### Exercise 8 - total net migration over 5 years
---

Using the Country Migration data sheet, display the record at position 10.  Using the column names to access the data in each column, add the five columns containing the net migration data together to calculate the total net migration over the 5 years between 2015 and 2019.

In [102]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name="Country Migration")
df[['net_per_10K_2015',	'net_per_10K_2016',	'net_per_10K_2017',	'net_per_10K_2018',	'net_per_10K_2019' ]].iloc[10].sum()

0.57

### Exercise 9 - formulating a text response

Using the Industry Migration data sheet, display the record at position 100.  Using the column names again to access the data in each column, calculate net migration over the 5 years from 2015 to 2019.

Then print the following message, adding the data where indicated:

The total net migration into `country` of skilled workers for the `industry name` industry, during the years 2015-2019 was `total_net_migration`

In [156]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name= "Industry Migration")
df.iloc[100]
df[['net_per_10K_2015',	'net_per_10K_2016',	'net_per_10K_2017',	'net_per_10K_2018',	'net_per_10K_2019' ]].iloc[100].sum()
df.iloc[100]
totalnet_migration=df['country_name'] ,df['industry_name'].iloc[100]
print(totalnet_migration)
df[['country_name', 'industry_name']].iloc[100]

(0       United Arab Emirates
1       United Arab Emirates
2       United Arab Emirates
3       United Arab Emirates
4       United Arab Emirates
                ...
5290                Zimbabwe
5291                Zimbabwe
5292                Zimbabwe
5293                Zimbabwe
5294                Zimbabwe
Name: country_name, Length: 5295, dtype: object, 'Capital Markets')

country_name     United Arab Emirates
industry_name         Capital Markets
Name: 100, dtype: object

### Exercise 10 - five text responses

Using the Industry Migration data sheet, calculate net migration (rounded to 1 decimal place) over the 5 years from 2015 to 2019 for the records at positions 1 to 5 and print the following message for each, adding the data where indicated:

The total net migration into `country` of skilled workers for the `industry name` industry, during the years 2015-2019 was `total_net_migration`

*Hint: use a for loop to get a record and do each calculation*

In [125]:
import pandas as pd
url = "https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true"
df = pd.read_excel(url,sheet_name= "Industry Migration")
df.iloc[100]
df[['net_per_10K_2015',	'net_per_10K_2016',	'net_per_10K_2017',	'net_per_10K_2018',	'net_per_10K_2019' ]].iloc[100].sum().round()

3412.0